FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY .env /app/.env
COPY frontend /app/frontend
EXPOSE 8501
CMD ["streamlit", "run", "frontend/home/home_ui.py", "--server.port=8501", "--server.address=0.0.0.0"]