FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    bash \
    curl \
    unzip \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt

COPY ava_dep /app/ava_dep
COPY processing_pipeline /app/processing_pipeline
COPY .env /app/.env
COPY files.sh /app/files.sh
RUN chmod +x /app/files.sh

EXPOSE 8000 5001


CMD ["bash", "/app/files.sh"]